name: Android CI

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write  
  
jobs:
  ###############################################################
  # Поиск секретов
  secrets:
    runs-on: ubuntu-24.04
    steps:
      # Скачивание кода
      - name: Checkout full history code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # вся история

      # Проверка репозитория на секреты. Gitleaks
      - name: Secrets searching (Gitleaks)
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Проверка репозитория на секреты. Trivy
      - name: Secrets searching (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'secret'
          format: 'sarif'
          output: 'trivy-secrets-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload secrets (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-secrets-results.sarif'
          category: 'trivy-secrets'
          
      # Сохранение отчета в CI Артефакты
      - name: Upload secrets to artifact (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: trivy-secrets-results
          path: trivy-secrets-results.sarif
          retention-days: 7          

      # Проверка конфигураций
      - name: Audit config (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-iac-results.sarif'

      # Выгрузка результатов в GitHub Code Scanning
      - name: Upload IaC misconfigurations (Trivy)
        uses: github/codeql-action/upload-sarif@v4        
        with:
          sarif_file: 'trivy-iac-results.sarif'
          category: 'trivy-iac'

      # Сохранение отчета в CI Артефакты
      - name: Upload IaC misconfigurations to artifact (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: trivy-iac-results
          path: trivy-iac-results.sarif
          retention-days: 7
  
  ###############################################################
  # Статический анализ (SAST Trivy)
  sast_trivy:
    runs-on: ubuntu-24.04
    needs: secrets
    steps:
      # Скачивание кода
      - name: Checkout code
        uses: actions/checkout@v7

      # Сканирование исходного кода. Trivy.
      - name: SAST (Trivy)
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: 'vuln,misconfig'
          format: 'sarif'
          output: 'trivy-sast-results.sarif'
          exit-code: '0'

      # Выгрузка результатов в GitHub Code Scanning (Trivy)
      - name: Upload SAST Results (Trivy)
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-sast-results.sarif'
          category: 'trivy-sast-results'

      # Сохранение отчета в CI Артефакты (Trivy)
      - name: Upload SAST Results (Trivy)
        uses: actions/upload-artifact@v7
        with:
          name: trivy-sast-results
          path: trivy-sast-results.sarif
          retention-days: 7

  ###############################################################
  # Статический анализ (SAST Semgrep)
  sast_semgrep:
    runs-on: ubuntu-24.04
    needs: secrets    
    container:
      image: semgrep/semgrep:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      # Сканирование 
      - name: SAST (Semgrep)
        run: semgrep scan --config=p/ci --sarif --output=semgrep-sast-results.sarif

      # Загрузка результатов в GitHub Security Dashboard (Semgrep)
      - name: Upload SAST Results (Semgrep)
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep-sast-results.sarif
          category: semgrep-sast-results

      # Сохранение отчета в CI Артефакты (Semgrep)
      - name: Upload SAST Results (Semgrep)
        uses: actions/upload-artifact@v7
        with:
          name: semgrep-sast-results
          path: semgrep-sast-results.sarif
          retention-days: 7          
          
  ###############################################################
  # Статический анализ (SAST CodeQL)
  sast_codeql:
    runs-on: ubuntu-24.04
    needs: secrets    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Init CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: 'java-kotlin'
          build-mode: none

      - name: Build
        run: ./gradlew build -x lint
        
      - name: Run CodeQL
        uses: github/codeql-action/analyze@v4

  ###############################################################
  # Сборка          
  build:
    runs-on: ubuntu-24.04
    needs: [sast_trivy, sast_semgrep, sast_codeql]
    steps:
    - uses: actions/checkout@v7
    - name: set up JDK 17
      uses: actions/setup-java@v6
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x lint
